### ISSUE TITLE
linux installation exception

### ISSUE THREAD

**Issue by abdelazizelesh** [billchen198318/bamboobsc#69]
We installed product in linux ubuntu 
java version "1.8.0_171"
apache-tomcat-8.5.32
Ubuntu 16.04.2 LTS
mysql: 5.7.22-0ubuntu0.16.04.1

we are getting belwo exception, please advice

2018-06-28 18:07:00 [] ERROR JobRunShell:211 - Job DEFAULT.bsc.job.SysExpressionJob threw an unhandled Exception:
java.lang.NoClassDefFoundError: Could not initialize class com.netsteadfast.greenstep.sys.BackgroundProgramUserUtils
        at com.netsteadfast.greenstep.job.BaseJob.logoutForBackgroundProgram(BaseJob.java:45)
        at com.netsteadfast.greenstep.job.impl.SysExpressionJobImpl.executeInternal(SysExpressionJobImpl.java:67)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-06-28 18:07:00 [] ERROR ErrorLogger:2425 - Job (DEFAULT.bsc.job.SysExpressionJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NoClassDefFoundError: Could not initialize class com.netsteadfast.greenstep.sys.BackgroundProgramUserUtils]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.netsteadfast.greenstep.sys.BackgroundProgramUserUtils
        at com.netsteadfast.greenstep.job.BaseJob.logoutForBackgroundProgram(BaseJob.java:45)
        at com.netsteadfast.greenstep.job.impl.SysExpressionJobImpl.executeInternal(SysExpressionJobImpl.java:67)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
2018-06-28 18:07:00 [] ERROR JobRunShell:211 - Job DEFAULT.core.job.SysExpressionJob threw an unhandled Exception:
java.lang.NoClassDefFoundError: Could not initialize class com.netsteadfast.greenstep.sys.BackgroundProgramUserUtils
        at com.netsteadfast.greenstep.job.BaseJob.logoutForBackgroundProgram(BaseJob.java:45)
        at com.netsteadfast.greenstep.job.impl.SysExpressionJobImpl.executeInternal(SysExpressionJobImpl.java:67)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-06-28 18:07:00 [] ERROR ErrorLogger:2425 - Job (DEFAULT.core.job.SysExpressionJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NoClassDefFoundError: Could not initialize class com.netsteadfast.greenstep.sys.BackgroundProgramUserUtils]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.netsteadfast.greenstep.sys.BackgroundProgramUserUtils
        at com.netsteadfast.greenstep.job.BaseJob.logoutForBackgroundProgram(BaseJob.java:45)
        at com.netsteadfast.greenstep.job.impl.SysExpressionJobImpl.executeInternal(SysExpressionJobImpl.java:67)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more

**Comment by billchen198318** [comment]
Hi 

1. are you has settings tomcat catalina.sh add item 
`JAVA_OPTS="-Xmx1280M -XX:+UseG1GC -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US"`

2. and you is use 0.7.4 release package? the release package tomcat8 is ver 8.0.50

**Comment by abdelazizelesh** [comment]
Hi,
I did all above steps, and same issue happens

**Comment by billchen198318** [comment]
upload full log file to as ZIP to me.

/tmp/greenstep-core.log
/tmp/greenstep-bsc.log

**Comment by billchen198318** [comment]
Hi, can you to folder gsbsc-web/WEB-INF/lib/ use md5 check command.
`# md5 core-base.jar` 
MD5 (core-base.jar) = d654d4e97b64b2ff97d0db5088781e73

And 
`# md5 core-lib.jar` 
MD5 (core-lib.jar) = aaacd2b27a71c34d3dfbbfa8cbf7cb7d

Check whether the same md5 value.

**Comment by abdelazizelesh** [comment]
Please find attached
https://drive.google.com/file/d/0B8zGCx8PI2igYVFJdFZlQ2hoa0plWk52WnlDZnA2dVZUMXBN/view?usp=drivesdk

**Comment by billchen198318** [comment]
Hi , help to check the MD5 value of core-base.jar and core-lib.jar

**Comment by billchen198318** [comment]
The issues can drop upload file, you no need use google drive to upload.

**Comment by billchen198318** [comment]
I find log, you has re-pack the web-apps( core-web, gsbsc-web ) as an WAR. i think is the WAR file no success.


01-Jul-2018 12:47:34.915 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/tacpi/sw/apache-tomcat-8.0.50/webapps/gsbsc-web.war
01-Jul-2018 12:47:48.306 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
01-Jul-2018 12:48:14.138 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/tacpi/sw/apache-tomcat-8.0.50/webapps/gsbsc-web.war has finished in 39,221 ms
01-Jul-2018 12:48:14.158 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/tacpi/sw/apache-tomcat-8.0.50/webapps/tacpi.war
01-Jul-2018 12:48:14.167 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/tacpi/sw/apache-tomcat-8.0.50/webapps/tacpi.war has finished in 9 ms
01-Jul-2018 12:48:14.195 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/tacpi/sw/apache-tomcat-8.0.50/webapps/core-web.war
01-Jul-2018 12:48:25.876 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
01-Jul-2018 12:48:41.998 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/tacpi/sw/apache-tomcat-8.0.50/webapps/core-web.war has finished in 27,803 ms

**Comment by abdelazizelesh** [comment]
tacpi@tacpi:~$ md5sum /home/tacpi/bamboobsc-0.7.4-RELEASE/bamboobsc-07/apache-tomcat-8.0.50/webapps/gsbsc-web/WEB-INF/lib/core-base.jar
d654d4e97b64b2ff97d0db5088781e73 


tacpi@tacpi:~$ md5sum /home/tacpi/bamboobsc-0.7.4-RELEASE/bamboobsc-07/apache-tomcat-8.0.50/webapps/gsbsc-web/WEB-INF/lib/core-lib.jar
aaacd2b27a71c34d3dfbbfa8cbf7cb7d

[Logs.zip](https://github.com/billchen198318/bamboobsc/files/2152828/Logs.zip)

**Comment by billchen198318** [comment]
I think maybe can try no re-pack as WAR, use default release package.

![20180701](https://user-images.githubusercontent.com/11564867/42135237-a923ab28-7d7a-11e8-946f-6f63a41801dd.png)

**Comment by abdelazizelesh** [comment]
I removed all packages and installed default release packages and same issue.

**Comment by billchen198318** [comment]
Hi, upload you new log file as zip to me.

**Comment by abdelazizelesh** [comment]
Please find zip folder
[Logs1.zip](https://github.com/billchen198318/bamboobsc/files/2152940/Logs1.zip)

**Comment by abdelazizelesh** [comment]
Hi, please find attached
[logs.zip](https://github.com/billchen198318/bamboobsc/files/2152978/logs.zip)

**Comment by billchen198318** [comment]
Hi can give me tomcat8 all log, thanks.

**Comment by billchen198318** [comment]
Hi first stop the expression job config. do stop the history score calculator job.

SQL:
`update tb_sys_expr_job set ACTIVE='N';`

root@localhost [bbcore]> update tb_sys_expr_job set ACTIVE='N';
Query OK, 8 rows affected (0.08 sec)
Rows matched: 8  Changed: 8  Warnings: 0

I think if you can try another computer environment, Because this problem is too strange.
The class `com.netsteadfast.greenstep.sys.BackgroundProgramUserUtils` is found in core-base.jar. but the error message is like cannot load it.
