### ISSUE TITLE
Centos 7 installation issue

### ISSUE THREAD

**Issue by sachinbanugariya** [billchen198318/bamboobsc#70]
hello,
i am trying to installation as per linux manual installation on centos 7.
it gives below error in logs:

2018-06-30 17:51:23 [] INFO  StdSchedulerFactory:1172 - Using default implementation for ThreadExecutor
2018-06-30 17:51:23 [] INFO  SchedulerSignalerImpl:61 - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2018-06-30 17:51:23 [] INFO  QuartzScheduler:240 - Quartz Scheduler v.2.2.3 created.
2018-06-30 17:51:23 [] INFO  LocalDataSourceJobStore:667 - Using db table-based data access locking (synchronization).
2018-06-30 17:51:23 [] INFO  LocalDataSourceJobStore:145 - JobStoreCMT initialized.
2018-06-30 17:51:23 [] INFO  QuartzScheduler:305 - Scheduler meta-data: Quartz Scheduler (v2.2.3) 'scheduler' with instanceId 'localhost.com1530352283453'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 8 threads.
  Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.

2018-06-30 17:51:23 [] INFO  StdSchedulerFactory:1327 - Quartz scheduler 'scheduler' initialized from an externally provided properties instance.
2018-06-30 17:51:23 [] INFO  StdSchedulerFactory:1331 - Quartz scheduler version: 2.2.3
2018-06-30 17:51:23 [] INFO  QuartzScheduler:2311 - JobFactory set to: org.springframework.scheduling.quartz.AdaptableJobFactory@20c617c
2018-06-30 17:51:23 [] WARN  ClassPathXmlApplicationContext:551 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scheduler' defined in URL [file:/home/bamboobsc-0.7.4-RELEASE/bamboobsc-07/apache-tomcat-8.0.50/webapps/core-web/WEB-INF/classes/applicationContext/applicationContext-STANDARD-QUARTZ.xml]: Invocation of init method failed; nested exception is org.quartz.JobPersistenceException: Couldn't retrieve trigger: Table 'bbcore.qrtz_TRIGGERS' doesn't exist [See nested exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'bbcore.qrtz_TRIGGERS' doesn't exist]
2018-06-30 17:51:23 [] INFO  DefaultAsyncJobExecutor:208 - Shutting down the default async job executor [org.activiti.engine.impl.asyncexecutor.DefaultAsyncJobExecutor].
2018-06-30 17:51:23 [] INFO  AcquireTimerJobsRunnable:115 - {} stopped async job due acquisition
2018-06-30 17:51:23 [] INFO  AcquireAsyncJobsDueRunnable:115 - {} stopped async job due acquisition
2018-06-30 17:51:23 [] INFO  ResetExpiredJobsRunnable:99 - {} stopped resetting expired jobs
2018-06-30 17:51:23 [] INFO  EhCacheManagerFactoryBean:187 - Shutting down EhCache CacheManager
2018-06-30 17:51:23 [] INFO  JMXPlatformImpl:76 - Unregistering existing Dozer JMX MBean [org.dozer.jmx:type=DozerAdminController].
2018-06-30 17:51:23 [] INFO  JMXPlatformImpl:76 - Unregistering existing Dozer JMX MBean [org.dozer.jmx:type=DozerStatisticsController].
2018-06-30 17:51:23 [] INFO  HikariDataSource:381 - HikariPool-2 - Shutdown initiated...
2018-06-30 17:51:23 [] INFO  HikariDataSource:383 - HikariPool-2 - Shutdown completed.
2018-06-30 17:51:23 [] INFO  USessLogHelperImpl:58 - delete tb_sys_usess data!...

please let me know the solution ASAP.
thanks.

**Comment by billchen198318** [comment]
Hi

The error message `com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'bbcore.qrtz_TRIGGERS' doesn't exist]`

The is you no settings MySQL server config, it need add `lower_case_table_names=1`

Please view:
https://github.com/billchen198318/bamboobsc#2-config-mysql-enable-lower_case_table_names1

**Comment by sachinbanugariya** [comment]
added mysql settings.
after much of time loading it gives below error:

==> /tmp/greenstep-bsc-mobile.log <==
2018-06-30 18:31:39 [] INFO  XmlWebApplicationContext:984 - Closing Root WebApplicationContext: startup date [Sat Jun 30 18:25:20 SGT 2018]; root of context hierarchy
2018-06-30 18:31:39 [] INFO  DefaultAsyncJobExecutor:208 - Shutting down the default async job executor [org.activiti.engine.impl.asyncexecutor.DefaultAsyncJobExecutor].
2018-06-30 18:31:39 [] INFO  AcquireTimerJobsRunnable:115 - {} stopped async job due acquisition
2018-06-30 18:31:39 [] INFO  AcquireAsyncJobsDueRunnable:115 - {} stopped async job due acquisition
2018-06-30 18:31:39 [] INFO  ResetExpiredJobsRunnable:99 - {} stopped resetting expired jobs
2018-06-30 18:31:39 [] INFO  EhCacheManagerFactoryBean:187 - Shutting down EhCache CacheManager
2018-06-30 18:31:39 [] DEBUG DiskStorePathManager:371 - Deleted directory ehcache_auto_created8957029216369596391diskstore
2018-06-30 18:31:39 [] INFO  JMXPlatformImpl:76 - Unregistering existing Dozer JMX MBean [org.dozer.jmx:type=DozerAdminController].
2018-06-30 18:31:39 [] INFO  JMXPlatformImpl:76 - Unregistering existing Dozer JMX MBean [org.dozer.jmx:type=DozerStatisticsController].
2018-06-30 18:31:39 [] INFO  HikariDataSource:381 - HikariPool-2 - Shutdown initiated...
2018-06-30 18:31:39 [] INFO  HikariDataSource:383 - HikariPool-2 - Shutdown completed.

==> /tmp/greenstep-core.log <==
2018-06-30 18:31:39 [] INFO  CamelHttpTransportServlet:87 - Destroyed CamelHttpTransportServlet[CamelServlet]
2018-06-30 18:31:40 [] INFO  QuartzScheduler:694 - Scheduler scheduler_$_localhost.com1530354225030 shutting down.
2018-06-30 18:31:40 [] INFO  QuartzScheduler:613 - Scheduler scheduler_$_localhost.com1530354225030 paused.
2018-06-30 18:31:40 [] INFO  QuartzScheduler:771 - Scheduler scheduler_$_localhost.com1530354225030 shutdown complete.
2018-06-30 18:31:40 [] INFO  UploadSupportUtils:170 - clean upload(CORE) temp begin...
2018-06-30 18:31:40 [] INFO  UploadSupportUtils:194 - end...
2018-06-30 18:31:40 [] INFO  UploadSupportUtils:170 - clean upload(BSC-MOBILE) temp begin...
2018-06-30 18:31:40 [] INFO  UploadSupportUtils:194 - end...
2018-06-30 18:31:40 [] INFO  USessLogHelperImpl:58 - delete tb_sys_usess data!...
2018-06-30 18:31:40 [] INFO  XmlWebApplicationContext:984 - Closing Root WebApplicationContext: startup date [Sat Jun 30 18:21:52 SGT 2018]; root of context hierarchy
2018-06-30 18:31:40 [] INFO  DefaultLifecycleProcessor:358 - Stopping beans in phase 2147483647
2018-06-30 18:31:40 [] INFO  SchedulerFactoryBean:765 - Shutting down Quartz Scheduler
2018-06-30 18:31:40 [] INFO  DefaultAsyncJobExecutor:208 - Shutting down the default async job executor [org.activiti.engine.impl.asyncexecutor.DefaultAsyncJobExecutor].
2018-06-30 18:31:40 [] INFO  AcquireAsyncJobsDueRunnable:115 - {} stopped async job due acquisition
2018-06-30 18:31:40 [] INFO  AcquireTimerJobsRunnable:115 - {} stopped async job due acquisition
2018-06-30 18:31:40 [] INFO  ResetExpiredJobsRunnable:99 - {} stopped resetting expired jobs
2018-06-30 18:31:40 [] INFO  EhCacheManagerFactoryBean:187 - Shutting down EhCache CacheManager
2018-06-30 18:31:40 [] DEBUG DiskStorePathManager:371 - Deleted directory ehcache_auto_created6497728846292583025diskstore
2018-06-30 18:31:40 [] INFO  HikariDataSource:381 - HikariPool-1 - Shutdown initiated...
2018-06-30 18:31:40 [] INFO  HikariDataSource:383 - HikariPool-1 - Shutdown completed.

==> /tmp/greenstep-bsc.log <==
2018-06-30 18:31:41 [] INFO  CamelHttpTransportServlet:87 - Destroyed CamelHttpTransportServlet[CamelServlet]
2018-06-30 18:31:41 [] INFO  QuartzScheduler:694 - Scheduler scheduler_$_localhost.com1530354662518 shutting down.
2018-06-30 18:31:41 [] INFO  QuartzScheduler:613 - Scheduler scheduler_$_localhost.com1530354662518 paused.
2018-06-30 18:31:41 [] INFO  QuartzScheduler:771 - Scheduler scheduler_$_localhost.com1530354662518 shutdown complete.
2018-06-30 18:31:41 [] INFO  CleanJasperReportTempDataForContextInitAndDestroy:45 - begin clean temp data....
2018-06-30 18:31:41 [] INFO  CleanJasperReportTempDataForContextInitAndDestroy:47 - end....
2018-06-30 18:31:41 [] INFO  UploadSupportUtils:170 - clean upload(BSC) temp begin...
2018-06-30 18:31:41 [] INFO  UploadSupportUtils:194 - end...
2018-06-30 18:31:41 [] INFO  XmlWebApplicationContext:984 - Closing Root WebApplicationContext: startup date [Sat Jun 30 18:28:37 SGT 2018]; root of context hierarchy
2018-06-30 18:31:41 [] INFO  SpringCamelContext:3312 - Apache Camel 2.19.3 (CamelContext: esb.BSC-SystemCamelContext) is shutting down
2018-06-30 18:31:41 [] INFO  DefaultShutdownStrategy:195 - Starting to graceful shutdown 2 routes (timeout 300 seconds)
2018-06-30 18:31:41 [] INFO  DefaultShutdownStrategy:668 - Route: route2 shutdown complete, was consuming from: servlet:/kpis
2018-06-30 18:31:41 [] INFO  DefaultShutdownStrategy:668 - Route: route1 shutdown complete, was consuming from: servlet:/api
2018-06-30 18:31:41 [] INFO  DefaultShutdownStrategy:259 - Graceful shutdown of 2 routes completed in 0 seconds
2018-06-30 18:31:42 [] INFO  SpringCamelContext:3401 - Apache Camel 2.19.3 (CamelContext: esb.BSC-SystemCamelContext) uptime 33.581 seconds
2018-06-30 18:31:42 [] INFO  SpringCamelContext:3402 - Apache Camel 2.19.3 (CamelContext: esb.BSC-SystemCamelContext) is shutdown in 0.263 seconds
2018-06-30 18:31:42 [] INFO  DefaultLifecycleProcessor:358 - Stopping beans in phase 2147483647
2018-06-30 18:31:42 [] INFO  SchedulerFactoryBean:765 - Shutting down Quartz Scheduler
2018-06-30 18:31:42 [] INFO  DefaultAsyncJobExecutor:208 - Shutting down the default async job executor [org.activiti.engine.impl.asyncexecutor.DefaultAsyncJobExecutor].
2018-06-30 18:31:42 [] INFO  AcquireTimerJobsRunnable:115 - {} stopped async job due acquisition
2018-06-30 18:31:42 [] INFO  AcquireAsyncJobsDueRunnable:115 - {} stopped async job due acquisition
2018-06-30 18:31:42 [] INFO  ResetExpiredJobsRunnable:99 - {} stopped resetting expired jobs
2018-06-30 18:31:42 [] INFO  EhCacheManagerFactoryBean:187 - Shutting down EhCache CacheManager
2018-06-30 18:31:42 [] DEBUG DiskStorePathManager:371 - Deleted directory ehcache_auto_created4440080447466722224diskstore
2018-06-30 18:31:42 [] INFO  HikariDataSource:381 - HikariPool-3 - Shutdown initiated...
2018-06-30 18:31:42 [] INFO  HikariDataSource:383 - HikariPool-3 - Shutdown completed.

**Comment by billchen198318** [comment]
Can you kill/stop the tomcat8 process.
and restart tomcat8, and give me the full log file.

**Comment by sachinbanugariya** [comment]
attached whole logs file.
[error.log](https://github.com/billchen198318/bamboobsc/files/2151643/error.log)

**Comment by billchen198318** [comment]
can you upload full geenstep-core.log , and greenstep-bsc.log to ZIP file upload to me. i need full.

**Comment by billchen198318** [comment]
/tmp/geenstep-core.log
/tmp/greenstep-bsc.log

**Comment by sachinbanugariya** [comment]
[greenstep-bsc.log](https://github.com/billchen198318/bamboobsc/files/2151663/greenstep-bsc.log)
[greenstep-core.log](https://github.com/billchen198318/bamboobsc/files/2151664/greenstep-core.log)

**Comment by billchen198318** [comment]
Hi you mysql version ? are you use 5.5 ver? or other.  I find error, the bambooBSC MySQL need 5.6 or later.

`
ERROR DbSqlSession:1223 - problem during schema create, statement alter table ACT_GE_BYTEARRAY 
add constraint ACT_FK_BYTEARR_DEPL 
foreign key (DEPLOYMENT_ID_) 
references ACT_RE_DEPLOYMENT (ID_)
java.sql.SQLException: Can't create table `bbcore`.`#sql-537_d70d` (errno: 121 "Duplicate key on write or update")
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
`

**Comment by sachinbanugariya** [comment]
mysql  Ver 15.1 Distrib 10.0.35-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by billchen198318** [comment]
The bambooBSC has use Activiti 6 BPMN framework, The bambooBSC use It need work with MySQL 5.6.
because bambooBSC SQL script bbcore.sql is use  Activiti 6 BPMN table for MySQL version.

**Comment by billchen198318** [comment]
It not work with MariaDB.

**Comment by sachinbanugariya** [comment]
yes but i already having 10.0.35-MariaDB, and innodb_version 5.6.39-83.1.

**Comment by sachinbanugariya** [comment]
ok you mean need of mysql version with 5.6 ?

**Comment by billchen198318** [comment]
yes, use MySQL 5.6 or 5.7. or later version.

**Comment by sachinbanugariya** [comment]
okay, thanks will try with mysql version instead of mariadb.

**Comment by billchen198318** [comment]
'bbcore.qrtz_z_bsc_TRIGGERS' doesn't exist]
    
config you mysql 14.14 add 
lower_case_table_names=1

**Comment by billchen198318** [comment]
Give tomcat8 all log file.

**Comment by billchen198318** [comment]
How many free memory ram size on you Linux environment?

**Comment by sachinbanugariya** [comment]
That is all log files which I seen in /TMP/.

Free RAM 1.6 GB.

**Comment by billchen198318** [comment]
/tmp log is not tomcat server log, https://www.google.com.tw/url?sa=t&source=web&rct=j&url=https://tomcat.apache.org/tomcat-8.0-doc/logging.html&ved=2ahUKEwjuhcfs04DcAhUL7WEKHcPaBVkQFjABegQIBRAB&usg=AOvVaw0v8oJ5oCEo4f3NpObRxTNu

**Comment by billchen198318** [comment]
In /home/bamboobsc-0.7.4-RELEASE/bamboobsc-07/apache-tomcat-8.0.50/logs directory

**Comment by sachinbanugariya** [comment]
Okay, thanks I will check and debug,
If not getting idea I will let post here.

**Comment by billchen198318** [comment]
Hi, if you click tree menu can success for work, you can ignore the Non core system not work message, it is a server site module check status.

LDAP need config apache shiro file, https://github.com/billchen198318/bamboobsc/issues/13 

https://shiro.apache.org/java-authentication-guide.html

The LDAP settings I cannot help you, because system environment are different.

**Comment by sachinbanugariya** [comment]
ok thanks for support.

**Comment by sachinbanugariya** [comment]
ldap file of shiro required GreenStepBaseFormAuthenticationFilter.java file,
but as per your document if we use 7z release version in code we not cloned that file,
i checked your main source code in that GreenStepBaseFormAuthenticationFilter.java file is present.
so maybe because of that is why ldap is not working as because of GreenStepBaseFormAuthenticationFilter.java is missing.
any comment for this ?
thanks

**Comment by billchen198318** [comment]
In core-web module : webapps/core-web/WEB-INF/classes/applicationContext/core/

copy `applicationContext-shiro-ldap-sample.xml` overwrite `applicationContext-shiro.xml`

and settings success LDAP server address with DN value.

set userDnTemplate item value to success, the is demo sample.
`<property name="userDnTemplate" value="CN={0},OU=people,DC=netsteadfast,DC=com" />`

**Comment by billchen198318** [comment]
And `ldapContextFactory` item `url` to success LDAP url.
The is demo sample.
`
<property name="url" value="ldap://192.168.1.200:389" />       
`

**Comment by sachinbanugariya** [comment]
2018-07-04 15:20:34 [] ERROR ContextLoader:350 - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiroFilter' defined in URL [file:/home/bamboobsc-0.7.4-RELEASE/bamboobsc-07/apache-tomcat-8.0.50/webapps/core-web/WEB-INF/classes/applicationContext/core/applicationContext-shiro.xml]: Cannot create inner bean 'util:map#ac14d3d' of type [org.springframework.beans.factory.config.MapFactoryBean] while setting bean property 'filters'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'util:map#ac14d3d': Cannot resolve reference to bean 'greenStepBaseFormAuthenticationFilter' while setting bean property 'sourceMap' with key [TypedStringValue: value [authc], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'greenStepBaseFormAuthenticationFilter' defined in URL [file:/home/bamboobsc-0.7.4-RELEASE/bamboobsc-07/apache-tomcat-8.0.50/webapps/core-web/WEB-INF/classes/applicationContext/core/applicationContext-shiro.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'accountService' of bean class [com.netsteadfast.greenstep.sys.GreenStepBaseFormAuthenticationFilter]: Bean property 'accountService' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1531)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1276)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:237)
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:703)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4861)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5322)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1126)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1868)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


getting above error after try LDAP shiro config,
also i copy and paste sys directory in running code from sorce code.
thanks

**Comment by sachinbanugariya** [comment]
yes i already set all ldap related settings already.

**Comment by billchen198318** [comment]
try remove `<property name="accountService" ref="core.service.AccountService"/>` of `greenStepBaseFormAuthenticationFilter` bean id in config xml file.

**Comment by sachinbanugariya** [comment]
==> catalina.2018-07-04.log <==
04-Jul-2018 17:54:26.005 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
04-Jul-2018 17:54:26.039 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 632123 ms
04-Jul-2018 17:54:26.175 INFO [http-nio2-8080-exec-2] org.apache.coyote.http11.AbstractHttp11Processor.process Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
        at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:235)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1045)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1097)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.run(Nio2Endpoint.java:1056)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)


==> catalina.out <==
04-Jul-2018 17:54:26.175 INFO [http-nio2-8080-exec-2] org.apache.coyote.http11.AbstractHttp11Processor.process Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
        at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:235)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1045)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1097)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.run(Nio2Endpoint.java:1056)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by billchen198318** [comment]
tomcat server.xml , the Connector config item , try add  `maxHttpHeaderSize="8192"`
I think the problem , maybe I not known how to help.

**Comment by billchen198318** [comment]
not 8192 , try to bigger the value.

**Comment by sachinbanugariya** [comment]
WARN  GreenStepBaseFormAuthenticationFilter:165 - LDAP naming error while attempting to authenticate user.

**Comment by billchen198318** [comment]
I think the code and config file need modify, the `GreenStepBaseAuthorizingLdapRealm` is extends `DefaultLdapRealm` , but need change to use `ActiveDirectoryRealm`.
the need 0.7.5 version will be do.

**Comment by billchen198318** [comment]
Must wait for some time

**Comment by sachinbanugariya** [comment]
ok, what you think how much time nearly it will take to develop and release new version ?

**Comment by billchen198318** [comment]
Because I am not working full-time on developing bambooBSC, i has normal for work and life, this part does not guarantee time. sorry.

**Comment by sachinbanugariya** [comment]
ok no problem thanks.

**Comment by billchen198318** [comment]
Hi , can you help me to test the config, add two parameter. but need change to success value. the only is a sample. before the config is lost `systemUsername` and `systemPassword` . 


```XML
<bean id="ldapContextFactory" class="org.apache.shiro.realm.ldap.JndiLdapContextFactory">
    	<property name="url" value="ldap://127.0.0.1:389" />  
    	<property name="systemUsername" value="cn=Manager,dc=example,dc=com" />
    	<property name="systemPassword" value="secret" />    	     
</bean>
```

**Comment by sachinbanugariya** [comment]
ok sure i will test that and let you know.

**Comment by sachinbanugariya** [comment]
WARN GreenStepBaseFormAuthenticationFilter:165 - LDAP naming error while attempting to authenticate user.

same issue seems also after above changes.

**Comment by sachinbanugariya** [comment]
hello,
once you developed code related ldap please let me know.
and i want to know that it also works for ldaps i.e 636 ?
thanks

**Comment by sachinbanugariya** [comment]
please let me know once ldap based login issue fixed.
thanks

**Comment by billchen198318** [comment]
are you use 0.7.6 version?

try the config file, it use `sAMAccountName` attribute


[applicationContext-shiro.xml.zip](https://github.com/billchen198318/bamboobsc/files/2782024/applicationContext-shiro.xml.zip)
