### ISSUE TITLE
error when i called the page way.jsp

### ISSUE THREAD

**Issue by luuigi** [billchen198318/bamboobsc#87]
![a](https://user-images.githubusercontent.com/48034579/53450558-2ead1d00-39e2-11e9-95d6-76c6dc197d25.png)

 I received the next message: 

type Informe de Excepción

mensaje /core-web/WebContent/pages/way.jsp (line: 4, column: 41) File "/struts-tags" not found

descripción El servidor encontró un error interno que hizo que no pudiera rellenar este requerimiento.

excepción

org.apache.jasper.JasperException: /core-web/WebContent/pages/way.jsp (line: 4, column: 41) File "/struts-tags" not found
	org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42)
	org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:443)
	org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:133)
	org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:168)
	org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:410)
	org.apache.jasper.compiler.Parser.parseDirective(Parser.java:475)
	org.apache.jasper.compiler.Parser.parseElements(Parser.java:1410)
	org.apache.jasper.compiler.Parser.parse(Parser.java:138)
	org.apache.jasper.compiler.ParserController.doParse(ParserController.java:242)
	org.apache.jasper.compiler.ParserController.parse(ParserController.java:102)
	org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:199)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:374)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:657)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by billchen198318** [comment]
check log file `greenstep-bsc.log` and `greenstep-core.log` in folder `C:\tmp\` or `/tmp/`
find the Error or Exception, provide the log file.

**Comment by luuigi** [comment]
I tried to found that folder but doestn’t exist 😕

Enviado desde mi iPhone

El 26 feb 2019, a la(s) 17:02, Bill chen <notifications@github.com<mailto:notifications@github.com>> escribió:


check log file greenstep-bsc.log and greenstep-core.log in folder C:\tmp\ or /tmp/
find the Error or Exception, provide the log file.

**Comment by billchen198318** [comment]
are you run the tomcat at C: or other disk-drive ? may you can check log at tomcat's log folder

**Comment by luuigi** [comment]
Hi @billchen198318 ! good morning from México, thanks for all!

I checked the tomcat logs:


**[TOMCAT7-STDERR]**
Feb 26, 2019 1:53:36 PM org.apache.catalina.startup.HostConfig undeploy
INFO: Undeploying context [/bamboobsc-0.7.6]
Feb 26, 2019 1:53:37 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory C:\xampp\tomcat\webapps\bamboobsc076
Feb 26, 2019 1:53:37 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory C:\xampp\tomcat\webapps\bamboobsc076 has finished in 40 ms

**[LOCALHOST]**
Feb 26, 2019 10:38:49 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [/bamboobsc076] threw exception [java.lang.ClassNotFoundException: org.apache.jsp.core_002dweb.WebContent.pages.way_jsp] with root cause
java.lang.ClassNotFoundException: org.apache.jsp.core_002dweb.WebContent.pages.way_jsp
	at java.net.URLClassLoader.findClass(Unknown Source)
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:132)
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:63)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:121)
	at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:172)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:369)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2462)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2451)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

@billchen198318  other thing,  My applicationcontent-datasource.properties files has the next data:
I don´t have a password now (temporary), my dataSource.jdbcUrl is good?
I created the database in the same server with all the tables that conteined the file bbcore.sql

#######################################################
for applicationContext-dataSource.xml
#######################################################
dataSource.driverClass=com.mysql.jdbc.Driver
dataSource.jdbcUrl=jdbc:mysql://localhost/bamboobsc076
#dataSource.jdbcUrl=jdbc:mysql://localhost/bbcore?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
dataSource.user=root
dataSource.password=
dataSource.maxPoolSize=8
dataSource.minPoolSize=2
#old only for C3P0 config
#dataSource.initialPoolSize=1
#dataSource.maxIdleTime=120

**Comment by luuigi** [comment]
The webpage send the next message:
 /core-web/WebContent/pages/way.jsp (line: 4, column: 41) File "/struts-tags" not found

I didnt find a folder or a file call struts-tags in the directory.

Even I checked with: 
dataSource.jdbcUrl=jdbc:mysql://localhost/bbcore?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
d

but not work. =(

**Comment by billchen198318** [comment]
i think you need  set password for MySQL server , and need set dataSource.password item, the password cannot blank , if install manual version are not easy, maybe change use VM-version(for VirtualBox) is good than manual install version.

**Comment by luuigi** [comment]
I change just like a "test" the code:
<%@ taglib uri="/struts-tags" prefix="s" %>  <-- not found
for
<%@ taglib uri="/struts" prefix="s" %>
 and I received the next info:


**type Informe de Excepción**

mensaje java.lang.ClassNotFoundException: org.apache.jsp.core_002dweb.WebContent.pages.way_jsp
descripción El servidor encontró un error interno que hizo que no pudiera rellenar este requerimiento.
excepción

org.apache.jasper.JasperException: java.lang.ClassNotFoundException: org.apache.jsp.core_002dweb.WebContent.pages.way_jsp
	org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:177)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:369)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

causa raíz

java.lang.ClassNotFoundException: org.apache.jsp.core_002dweb.WebContent.pages.way_jsp
	java.net.URLClassLoader.findClass(Unknown Source)
	org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:132)
	org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:63)
	org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:172)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:369)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

nota La traza completa de la causa de este error se encuentra en los archivos de diario de Apache Tomcat/7.0.56.

**Comment by billchen198318** [comment]
Hi sir, The error is not about with struts-tags , the main problem is application cannot success connection to MySQL database. because the Spring init fail, so will show this error message.

**Comment by luuigi** [comment]
> i think you need set password for MySQL server , and need set dataSource.password item, the password cannot blank , if install manual version are not easy, maybe change use VM-version(for VirtualBox) is good than manual install version.

Hi @billchen198318 

I checked that part and I created a new user with passwordbut did´t work =(

#######################################################
#	for applicationContext-dataSource.xml
#######################################################
dataSource.driverClass=com.mysql.jdbc.Driver
#dataSource.jdbcUrl=jdbc:mysql://localhost/bamboobsc076
dataSource.jdbcUrl=jdbc:mysql://localhost/bbcore?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
dataSource.user=scorecard
dataSource.password=!m!.2019
dataSource.maxPoolSize=8
dataSource.minPoolSize=2
# old only for C3P0 config
#dataSource.initialPoolSize=1
#dataSource.maxIdleTime=120

**Comment by billchen198318** [comment]
can provide upload log file is the issues

**Comment by billchen198318** [comment]
recommed you change use VM-version

**Comment by luuigi** [comment]
> Hi sir, The error is not about with struts-tags , the main problem is application cannot success connection to MySQL database. because the Spring init fail, so will show this error message.

Ok @billchen198318  I set a password in my conection account:

#######################################################
#	for applicationContext-dataSource.xml
#######################################################
dataSource.driverClass=com.mysql.jdbc.Driver
#dataSource.jdbcUrl=jdbc:mysql://localhost/bamboobsc076
dataSource.jdbcUrl=jdbc:mysql://localhost/bbcore?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
dataSource.user=scorecard
dataSource.password=!m!.2019
dataSource.maxPoolSize=8
dataSource.minPoolSize=2
# old only for C3P0 config
#dataSource.initialPoolSize=1
#dataSource.maxIdleTime=120

and I return the line code like originality:

<%@ taglib uri="/struts-tags" prefix="s" %>

and my Database is called bbcore:
[http://prntscr.com/mqwr7h](url)

with this parameters I received this message:

Estado HTTP 500 - /core-web/WebContent/pages/way.jsp (line: 4, column: 41) File "/struts-tags" not found

type Informe de Excepción

mensaje /core-web/WebContent/pages/way.jsp (line: 4, column: 41) File "/struts-tags" not found

descripción El servidor encontró un error interno que hizo que no pudiera rellenar este requerimiento.

excepción

org.apache.jasper.JasperException: /core-web/WebContent/pages/way.jsp (line: 4, column: 41) File "/struts-tags" not found
	org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42)
	org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:443)
	org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:133)
	org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:168)
	org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:410)
	org.apache.jasper.compiler.Parser.parseDirective(Parser.java:475)
	org.apache.jasper.compiler.Parser.parseElements(Parser.java:1410)
	org.apache.jasper.compiler.Parser.parse(Parser.java:138)
	org.apache.jasper.compiler.ParserController.doParse(ParserController.java:242)
	org.apache.jasper.compiler.ParserController.parse(ParserController.java:102)
	org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:199)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:374)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:657)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

nota La traza completa de la causa de este error se encuentra en los archivos de diario de Apache Tomcat/7.0.56.

Help me please! I want to work with your software, is soooo great!!! =)

**Comment by luuigi** [comment]
> recommed you change use VM-version

I install the app in a windows server 2012 
wich VM-version do you recommend? =(
The logs news is:

**[LOCALHOST]**
Feb 27, 2019 9:37:19 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [/bamboobsc076] threw exception [java.lang.ClassNotFoundException: org.apache.jsp.core_002dweb.WebContent.pages.way_jsp] with root cause
java.lang.ClassNotFoundException: org.apache.jsp.core_002dweb.WebContent.pages.way_jsp
	at java.net.URLClassLoader.findClass(Unknown Source)
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:132)
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:63)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:121)
	at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:172)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:369)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2462)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2451)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by billchen198318** [comment]
Tomcat/7.0.56 ??? Are you use 0.7.6 RELEASE package??? the bambooBSC 0.7.6 are work with tomcat 8.5.35

**Comment by billchen198318** [comment]
VM-version download from: 
https://github.com/billchen198318/bamboobsc/releases/download/v0.7.6/bamboobsc-0.7.6-RELEASE-VM.7z

**Comment by billchen198318** [comment]
Use VM-version , you no need to config MySQL and settings config file. only need install VirtualBox and import the VM file to VirtualBox

**Comment by luuigi** [comment]
Done!!!!!! I use VM-version, is great!!!!!! thanks for your timeeeeeee @billchen198318  

=)
